# Create a function that receives three integers: x, y and z. 
# If any of them are 0 or negative, or if they are greater than 255, 
# the function should return -1 The function should return the z element of the series generated by x and y. 
# For example: If the function receives x=5, y=3, z=3, it will return 64, 
# because 64 is the 3th element in the generated series when x=5 and y=3. 
# The function will receive 3 integers, return an integer.

def serieXD(x: int, y: int, z: int) -> int:
    serie, numberX, numberY, numberZ = [], x, y, z
    if numberX < 1 or numberX > 255: return -1
    elif numberY < 1 or numberY > 255: return -1
    elif numberZ < 1 or numberZ > 255: return -1
    else:
        init: int = int(str(numberX) + str(numberY))
        for i in range(init, init+255):
            if(i%2==1):
                serie.append(int(str(numberX)+str(numberY)))
            else:
                serie.append(int(str(numberY)+str(numberX)))
                numberX = int(numberX) + 1
                numberY = int(numberY) + 1

        return serie[numberZ-1]

print(serieXD(5,3,3))
